import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Navbar from "@/components/navbar";
import TanstackProvider from "@/components/providers/tanstack-provider";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YakShop",
  description: "Generated by Ryan Lisse",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="bg-stone-50 dark:bg-gray-950">
              <Navbar />
              {children}
              <Toaster />
            </main>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
